_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

# Protein training typically needs more epochs
min_epochs: 5
max_epochs: 10

# Use GPU if available, fallback to CPU
accelerator: auto
devices: auto

# Mixed precision for protein models (memory intensive)
precision: "16-mixed" #TODO: CONSIDER BF16

# Validation frequency (protein training is slow)
check_val_every_n_epoch: 1

# Deterministic training for reproducibility
deterministic: False

# Gradient clipping for stability
gradient_clip_val: 1.0
gradient_clip_algorithm: "norm"

# Accumulate gradients to simulate larger batch sizes
# accumulate_grad_batches: 2
# Log every N steps for monitoring


