_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

# Protein training typically needs more epochs
min_epochs: 5
max_epochs: 40

# Use GPU if available, fallback to CPU
accelerator: auto
devices: auto

# Mixed precision for protein models (memory intensive)
precision: "bf16-mixed"

# Validation frequency (protein training is slow)
check_val_every_n_epoch: 1

# Disable sanity check to avoid _go_dicts KeyError during initialization
num_sanity_val_steps: 0

# Deterministic training for reproducibility
deterministic: False

# Gradient clipping for stability
gradient_clip_val: 1.0
gradient_clip_algorithm: "norm"

# Accumulate gradients to simulate larger batch sizes
accumulate_grad_batches: 2
# Log every N steps for monitoring


 #NOTE: PROFILE SHOULD BE CONSIDERED FOR LARGE RUN 
# Enable PyTorch profiler for detailed performance analysis
# profiler: pytorch

# Log metrics every 10 steps instead of every step to avoid throughput monitoring issues
log_every_n_steps: 1

# Enable progress bar without throughput monitoring issues

# NOTE: If you want progress bar back, use log_every_n_steps: 10 or higher
# enable_progress_bar: true
