_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

# Protein training typically needs more epochs
min_epochs: 5
max_epochs: 10

# Use GPU if available, fallback to CPU
accelerator: auto
devices: auto

# Mixed precision for protein models (memory intensive)
precision: "bf16-mixed"

# Validation frequency (protein training is slow)
check_val_every_n_epoch: 1

# Disable sanity check to avoid _go_dicts KeyError during initialization
num_sanity_val_steps: 0

# Deterministic training for reproducibility
deterministic: False

# Gradient clipping for stability
gradient_clip_val: 1.0
gradient_clip_algorithm: "norm"

# Accumulate gradients to simulate larger batch sizes
accumulate_grad_batches: 5
# Log every N steps for monitoring


