defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_fmax_{val/Fmax:.4f}"
  monitor: "val/Fmax"  # Monitor Fmax for protein function prediction
  mode: "max"
  save_last: False
  save_top_k: 1  # Save top 1 model for early testing 
  auto_insert_metric_name: False
  every_n_epochs: ${trainer.check_val_every_n_epoch}

early_stopping:
  monitor: "val/Fmax"  #NOTE: Monitor Fmax for protein function prediction (higher is better)
  patience: 3  # More patience for protein training (slower convergence)
  mode: "max"
  min_delta: 0.001  # Minimum improvement threshold
  check_finite: True
  stopping_threshold: null  # No specific stopping threshold for Fmax
  divergence_threshold: null
  check_on_train_epoch_end: False

model_summary:
  max_depth: 1  # Limit depth for complex protein models

rich_progress_bar:
  leave: True
  theme:
    description: "white"
    progress_bar: "#6206E0"
    progress_bar_finished: "#6206E0"
    progress_bar_pulse: "#6206E0"
    batch_progress: "white"
    time: "grey54"
    processing_speed: "grey70"
    metrics: "white" 